### ISSUE TITLE
Consolidate HtmlBuilder and HtmlParser classes

### ISSUE THREAD

**Issue by helephant** [Morriphi/HTTPDriver#12]
Both these classes make it easy to go from a HTML string to HTML agility pack node objects.

Question: do we need to wrap the HTML node objects or should we just expose them directly?

**Comment by Morriphi** [comment]
I've removed the HtmlParser, it was only used in tests. 

Going forward I think all the parsing logic should be done in browser, meaning HttpDriver should have no dependency on Agility Pack and Browser should have no dependency on the selenium interfaces.

We would then keep a nice clean separation between what is essentially browser logic and what we expose for the WebDriver interface. 

Hope that made sense :-) what does everyone else think?

**Comment by helephant** [comment]
If we abstract away the Html Agility pack, won't we need to create another object with pretty much the HtmlNode information? The WebDriver layer represents them as WebElements anyway. Should we really introduce a third way to represent a HTML element?

**Comment by Morriphi** [comment]
That's true, if you look at the way I abstracted title I was thinking we might have a simpler abstraction. But I think you're right we will end up exposing so much that we might as well just expose the WebElemet to the WedDriver layer.

Will be interesting to see how it evolves.

**Comment by Morriphi** [comment]
WedDriver :-)

**Comment by helephant** [comment]
I think we should start off just exposing HtmlNodes from the Browser and then turning them into WebElements in the WebDriver layer. I don't think the browser should know about the WebDriver IWebElement interface.

**Comment by Morriphi** [comment]
Removed HtmlParser
